# Generated by Django 3.2 on 2023-06-23 01:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seekers', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EmployerProfile', to=settings.AUTH_USER_MODEL, verbose_name='EmployerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job title')),
                ('description', models.TextField(blank=True, max_length=555, null=True, verbose_name='Job description')),
                ('city', models.CharField(blank=True, max_length=55, null=True, verbose_name='Location')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('industry', models.CharField(blank=True, max_length=155, null=True, verbose_name='Industry')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=50, null=True, verbose_name='job_status')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobRecruiter', to='employers.employerprofile')),
                ('required_skills', models.ManyToManyField(blank=True, to='core.Skill', verbose_name='Required Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Reviewing', 'Reviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=50, null=True, verbose_name='Application_status')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.seekerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employers.job')),
            ],
        ),
    ]
