# Generated by Django 4.2 on 2023-04-06 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import seekers.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, verbose_name="skill")),
            ],
        ),
        migrations.CreateModel(
            name="SeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="State "
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=50, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ethnicity", "Ethnicity"),
                            ("African", "African"),
                            ("African American", "African American"),
                            ("Arab", "Arab"),
                            ("Asian", "Asian"),
                            (
                                "Any other Asian background",
                                "Any other Asian background",
                            ),
                            ("Bangladeshi", "Bangladeshi"),
                            ("Caribbean", "Caribbean"),
                            ("Chinese", "Chinese"),
                            ("English", "English"),
                            ("Gypsy or Irish Traveller", "Gypsy or Irish Traveller"),
                            ("Hispanic", "Hispanic"),
                            ("Indian", "Indian"),
                            ("Irish", "Irish"),
                            (
                                "Mixed or Multiple background",
                                "Mixed or Multiple background",
                            ),
                            (
                                "Mixed or Multiple ethnic groups",
                                "Mixed or Multiple ethnic groups",
                            ),
                            ("Native American", "Native American"),
                            ("Northern Irish", "Northern Irish"),
                            ("Pacific Islander", "Pacific Islander"),
                            ("Pakistani", "Pakistani"),
                            ("Scottish", "Scotish"),
                            ("White", "White"),
                            ("White and Black African", "White and Black African"),
                            ("White and Black Caribbean", "White and Black Caribbean"),
                            ("Welsh", "Welsh"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Ethnicity",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to=seekers.models.cv_filepath
                    ),
                ),
                (
                    "passport",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=seekers.models.passport_filepath,
                    ),
                ),
                (
                    "visa",
                    models.FileField(
                        blank=True, null=True, upload_to=seekers.models.visa_filepath
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seeker_profiles",
                        to="seekers.skill",
                        verbose_name="Skills",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SeekerProfile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "seeker_profile",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "seeker_profile",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
        ),
    ]
