# Generated by Django 4.2 on 2023-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tile", models.CharField(blank=True, max_length=55, null=True)),
                ("snippet", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, max_length=2255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("answer", models.TextField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tile", models.CharField(blank=True, max_length=55, null=True)),
                ("snippet", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, max_length=2255, null=True)),
            ],
        ),
    ]
