
[phases.setup]
aptPkgs = ["...", "libstdc++6", "binutils", "libstdc++6", "libheif-dev", "libheif1", "poppler-utils", "libjson-c-dev", "libproj-dev", "gdal-bin", "libgdal-dev", "python3-gdal"]
nixPkgs = ["...", "libheif", "libstdc++6", "binutils", "libstdc++6", "libheif-dev", "libheif1", "poppler-utils", "libjson-c-dev", "libproj-dev", "gdal-bin", "libgdal-dev", "python3-gdal"]
